language: php
sudo: yes
dist: trusty

php:
  - '5.4'
  - '5.6'

before_script:
  - phpenv install 5.4.45
  - phpenv global 5.4.45
  - php-config --extension-dir
  - phpize
  - ./configure
  - make

script:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1 make test

